---
title: "new-task-writeup-viz-pipeline"
author: "Emily Hu"
date: "2/27/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(stringr)
library(markdown)
library(qualtRics)
library(dplyr)
library(tidyverse)
```

# Basic setup
(Not pushed to GitHub)

# Pull in Survey Data
```{r}
surveys <- all_surveys()

task_writing_survey_id <- surveys$id[2]

df.survey_results <- fetch_survey(
  surveyID = task_writing_survey_id,
  save_dir = "."
)
```

# Check timing
```{r}
df.survey_results %>%
  mutate(
    Duration = EndDate-StartDate
  ) %>%
  summarize(
    medianDuration = median(Duration)
  )
```

```{r}
colnames(df.survey_results)

df.survey_results_cleaned <-df.survey_results %>%
  select(
    `task-name`,
    `GitHub-id`,
    `stimulus-complex`,
    `goal-directives`,
    skills,
    `ui-ux`,
    `allowed-gr-proc`,
    `GitHub-link`,
    `external-resources`
  )

df.survey_results_cleaned
```

# Generate .md Files
```{r}
for(i in 1:nrow(df.survey_results_cleaned)){
  row <- df.survey_results_cleaned[i,]
  task_title <- paste0("# ",toString(row$`task-name`),"\n\n")
  author <- paste0("Mapped by: ",toString(row$`GitHub-id`)," \n\n")
  stim_complex <- paste0("## 1. Stimulus Complex \n",toString(row$`stimulus-complex`),"\n\n")
  goal_directives <- paste0("## 2. Goal Directives \n",toString(row$`goal-directives`),"\n\n")
  allowed_group_processes <- "## 3. Allowed Group Processes \n" 
  group_proc_info <- "The following details are not the main parts of the task, but rather additional information about ways in which participants could interact.\n\n"
  skills <- paste0("### Skills \n",toString(row$`skills`),"\n\n")
  uiux <- paste0("### UI-UX Allowed Processes\n",toString(row$`skills`),"\n\n")
  other_allowed_proc <- paste0("### Other Allowed Processes\n",toString(row$`allowed-gr-proc`),"\n\n")
  github <- paste0("## GitHub Link \n",toString(row$`GitHub-link`))

  total_markdown_string <- paste0(task_title,
                                  author,
                                  stim_complex,
                                  goal_directives,
                                  allowed_group_processes,
                                  group_proc_info,
                                  skills,
                                  uiux,
                                  other_allowed_proc,
                                  github)
  
  file_title <- paste0("../tasks/summaries/",row$`task-name`,"-writeup.md")
  
  # only write the file if it doesn't already exist
  if(file.exists(file_title) == FALSE){
    writeup_file <- file(file_title, "w") # Create Rmarkdown file
    cat(total_markdown_string, file = writeup_file) # Write your content to Rmarkdown file
    close(writeup_file)
  }
}
```

# Generate a CSV with task names in one column and HTML in a second column
This will enable us to paste directly into the task mapping survey.
```{r}
df.task_map_format <- data.frame(matrix(ncol = 2, nrow = 0))
colnames(df.task_map_format) <- c('Task Name', 'Task Writeup')

for(i in 1:length(df.survey_results$`task-name`)){
  task_name <- df.survey_results$`task-name`[i]
  file_title <- paste0("../tasks/summaries/",task_name,"-writeup.md")
  
  txt <- read_file(file_title)
  txt_html <- markdownToHTML(text = txt,
                             fragment.only =  T)
  
  # remove the mapper name and the github link
  txt_html <- str_remove(txt_html, "<p>Mapped by: .*</p>") %>%
      str_remove("<h2>.*GitHub Link.*") %>%
      str_remove("<a href=.*</a>") %>%
      str_remove("<p></p>")
  
  # remove line breaks
  txt_html <- str_replace_all(txt_html, "[\r\n]" , "")
  
  # add better line breaks
  txt_html <- str_replace_all(txt_html, "<h2>", "<br><h2>") %>%
              str_replace_all("<h1>", "<h2>") %>%
              str_replace_all("</h1>", "</h2>")
  
  new_row = data.frame(
    'Task Name'= task_name,
    'Task Writeup' =  txt_html
  )
  
  df.task_map_format <- rbind(df.task_map_format, new_row)
}
```


```{r}
df.task_map_format %>% write_csv('./html/task-htmls.csv')
```

