import {showPracticeStage} from '../gameConfiguration';

// Task Configuration Instances
export const TASK_CONFIG = [
  // Logic Problem Zero - Practice Round
  {
    calculateScore: !showPracticeStage,
    name: 'Logic Problem instance zero',
    story:
      "Charlie is quite proud of her little shell collection. Match each shell's name to its primary colors and the year in which Charlie found it.",
    clues: [
      'The seashell found in 2002 is either the black and white shell or the honey cerith shell.',
      'The pink and white shell was found 3 years before the coquina shell.',
      'The horned turban shell is brown and yellow.',
      'The shark eye shell was found 3 years before the pink and white shell.',
    ],
    top: [
      '',
      'coquina',
      'honey cerith',
      'horned turban',
      'shark eye',
      'black - white',
      'blue - white',
      'brown - yellow',
      'pink - white',
    ],
    left: ['2002', '2005', '2008', '2011'],
    headers: ['Year', 'Name', 'Colors'],
    answers: [
      'X',
      'X',
      'X',
      '✓',
      '✓',
      'X',
      'X',
      'X',
      'X',
      '✓',
      'X',
      'X',
      'X',
      'X',
      'X',
      '✓',
      '✓',
      'X',
      'X',
      'X',
      'X',
      '✓',
      'X',
      'X',
      'X',
      'X',
      '✓',
      'X',
      'X',
      'X',
      '✓',
      'X',
    ],
    grid: [
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
    ],
    numEtherpads: 1,
  },
  // Logic Problem One
  {
    calculateScore: true,
    name: 'Logic Problem instance one',
    story:
      "Jane works at 'Superfood Smoothies,' and she's got a long line of customers waiting for their orders. Using only the clues below, match each customer to his or her order type and price.",
    clues: [
      'Anna paid $8.75.',
      'The person who requested chia seeds paid 2 dollars more than Jay.',
      'The customer who paid $8.75 asked for Acai berries.',
      'Shawn paid less than the customer who requested quinoa.',
    ],
    top: ['', 'Jay', 'Shawn', 'Katie', 'Anna', 'kale', 'chia seeds', 'quinoa', 'acai berries'],
    left: ['$6.75', '$7.75', '$8.75', '$9.75'],
    headers: ['Price', 'Name', 'Order Type'],
    answers: [
      'X',
      '✓',
      'X',
      'X',
      '✓',
      'X',
      'X',
      'X',
      '✓',
      'X',
      'X',
      'X',
      'X',
      'X',
      '✓',
      'X',
      'X',
      'X',
      'X',
      '✓',
      'X',
      'X',
      'X',
      '✓',
      'X',
      'X',
      '✓',
      'X',
      'X',
      '✓',
      'X',
      'X',
    ],
    grid: [
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
    ],
    numEtherpads: 1,
  },
  // Logic Problem Two
  {
    calculateScore: true,
    name: 'Logic Problem instance two',
    story:
      'Delilah Miller, the award-winning film director, has just finished casting her newest project. Help her set the schedule by matching each actor to their acting fee and film date.',
    clues: [
      'John will make $15,000 less than the actor filming on September 8th.',
      'John is either the man making $115,000 or the person filming on September 1st.',
      'The actor filming on September 1st will make $15,000 more than Scott.',
      'The person making $85,000 will film on September 15th.',
      'Mac will film on September 29th.',
    ],
    top: [
      '',
      'Scott',
      'Mac',
      'Mia',
      'John',
      'September 1',
      'September 8',
      'September 15',
      'September 29',
    ],
    left: ['$85,000', '$100,000', '$115,000', '$130,000'],
    headers: ['Acting Fee', 'Name', 'Film Date'],
    answers: [
      '✓',
      'X',
      'X',
      'X',
      'X',
      'X',
      '✓',
      'X',
      'X',
      'X',
      'X',
      '✓',
      '✓',
      'X',
      'X',
      'X',
      'X',
      'X',
      '✓',
      'X',
      'X',
      '✓',
      'X',
      'X',
      'X',
      '✓',
      'X',
      'X',
      'X',
      'X',
      'X',
      '✓',
    ],
    grid: [
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
    ],
    numEtherpads: 1,
  },
  // Logic Problem Three
  {
    calculateScore: true,
    name: 'Logic Problem instance three',
    story:
      "Porter is a 'tiny home' enthusiast - he builds small, portable homes and sells them to others interested in the movement. Using only the clues below, determine the size and cost of each of his customer's tiny homes, as well as the city it will be delivered to.",
    clues: [
      "The Swift's structure is 30 sq ft smaller than the Dylan's house.",
      "The $38,000 house is somewhat larger than the Swift's house.",
      "The Bridgers' structure is 30 sq ft smaller than the $25,000 home.",
      'Of the 140 sq ft house and the $29,000 house, one is for the Rogers and the other is for the Dylans.',
    ],
    top: ['', 'Bridgers', 'Swift', 'Dylan', 'Rogers', '$25,000', '$29,000', '$35,000', '$38,000'],
    left: ['95 sq ft', '110 sq ft', '125 sq ft', '140 sq ft'],
    headers: ['Size', 'Name', 'Price'],
    answers: [
      'X',
      '✓',
      'X',
      'X',
      'X',
      'X',
      '✓',
      'X',
      '✓',
      'X',
      'X',
      'X',
      'X',
      'X',
      'X',
      '✓',
      'X',
      'X',
      '✓',
      'X',
      'X',
      '✓',
      'X',
      'X',
      'X',
      'X',
      'X',
      '✓',
      '✓',
      'X',
      'X',
      'X',
    ],
    grid: [
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
      ' ',
    ],
    numEtherpads: 1,
  },
];
